pythonProject5/RentX/RentX/urls.py
from django.contrib import admin
from django.urls import path, include

from .import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .import views

urlpatterns = [
    #error page
    path('404',views.Error404,name='404'),


    path('admin/', admin.site.urls),
    path('base/',views.BASE,name='base'),
    path('', views.HOME, name='home'),
    path('about', views.ABOUT, name='about'),
    path('contact', views.CONTACT, name='contact'),
    path('product', views.PRODUCT, name='product'),
    path('product/filter-data',views.filter_data,name="filter-data"),


    path('product/<slug:slug>',views.PRODUCT_DETAILS, name='product_detail'),


    # account urls
    path('account/my-account', views.MY_ACCOUNT, name='my_account'),
    path('account/register', views.REGISTER, name='handleregister'),
    path('account/login', views.LOGIN, name='handlelogin'),
    path('account/profile',views.PROFILE,name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/update',views.PROFILE_UPDATE,name="profile_update"),



    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),

    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),

    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),

    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),

    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),

    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),


] +static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pythonProject5/RentX/app/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.db.models.signals import pre_save
# Create your models here.
class slider(models.Model):
    DISCOUNT_DEAL = (
        ('HOT DEALS','HOT DEALS'),
        ('New Arraivels', 'New Arraivels'),
    )

    Image = models.ImageField(upload_to='media/slider_imgs')
    Discount_Deal = models.CharField(choices=DISCOUNT_DEAL,max_length=100)
    SALE = models.IntegerField()
    Brand_Name = models.CharField(max_length=200)
    Discount = models.IntegerField()
    Link = models.CharField(max_length=200)

    def __str__(self):
        return self.Brand_Name


class banner_area(models.Model):

    image = models.ImageField(upload_to='media/banner_img')
    Discount_Deal = models.CharField(max_length=100)
    Quote = models.CharField(max_length=100)
    Discount = models.IntegerField()
    Link = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.Quote


class Main_Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Category(models.Model):
    main_category = models.ForeignKey(Main_Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name + " -- " + self.main_category.name

class Sub_Category(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.category.main_category.name + " -- " + self.category.name + " -- " + self.name




class Section(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Color(models.Model):
    code = models.CharField(max_length=100)
    def __str__(self):
        return self.code


class Brand(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name




class Product(models.Model):
    total_quantity = models.IntegerField()
    Availability = models.IntegerField()
    featured_image = models.CharField(max_length=100)
    product_name = models.CharField(max_length=100)
    Brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True)
    price = models.IntegerField()
    Discount = models.IntegerField()
    Product_information = RichTextField()
    model_Name = models.CharField(max_length=100)
    Categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE,null=True)

    Tags = models.CharField(max_length=100)
    Description = RichTextField()
    section = models.ForeignKey(Section, on_delete=models.DO_NOTHING)
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("product_detail", kwargs={'slug': self.slug})

    class Meta:
        db_table = "app_Product"


def create_slug(instance, new_slug=None):
    slug = slugify(instance.product_name)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, Product)
class Product_Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    Image_url = models.CharField(max_length=200)


class Additional_Information(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.CharField(max_length=100)
    detail = models.CharField(max_length=100)

pythonProject5/RentX/templates/includes/footer.html
 <footer>
        <div class="fotter-area d-dark-bg">
            <div class="footer__top pt-80 pb-15">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-5 col-lg-4 order-last-md">
                            <div class="row">
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Customer Care</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="faq.html">New vendors</a></li>
                                                    <li><a href="faq.html">How to use Account</a></li>
                                                    <li><a href="faq.html">Rent a thing</a></li>
                                                    <li><a href="faq.html">Payment Methods</a></li>
                                                    <li><a href="faq.html">Delivery &amp; Dispatch</a></li>
                                                    <li><a href="faq.html">Problems with Order</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Customer Service</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="faq.html">Help Center</a></li>
                                                    <li><a href="faq.html">Contact Us</a></li>

                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-8 order-first-md">
                            <div class="footer__top-left">
                                <div class="row">

                                    <div class="col-xl-7 col-lg-6 col-md-6 col-sm-6">
                                        <div class="row">

                                            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                                <div class="footer__widget">
                                                    <div class="footer__widget-title">
                                                        <h4>My Account</h4>
                                                    </div>
                                                    <div class="footer__widget-content">
                                                        <div class="footer__link">
                                                            <ul>

                                                                <li><a href="checkout.html">Checkout</a></li>
                                                                <li><a href="cart.html">Rent Cart</a></li>
                                                                <li><a href="wishlist.html">Wishlist</a></li>
                                                                <li><a href="faq.html">Terms &amp; Conditions &amp;</a></li>
                                                                <li><a href="faq.html">Redeem Voucher</a></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                    <div class="footer__widget">
                                        <div class="footer__widget-title">
                                            <h4>Quick Links</h4>
                                        </div>
                                        <div class="footer__widget-content">
                                            <div class="footer__link">
                                                <ul>
                                                    <li><a href="contact.html">Store Location</a></li>
                                                    <li><a href="my-account.html">My account</a></li>
                                                    <li><a href="contact.html">Rent Item Tracking</a></li>
                                                    <li><a href="faq.html">FAQs</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div></div>
                                    </div><div class="col-xl-5 col-lg-6 col-md-6 col-sm-6">
                                        <div class="footer__widget">
                                            <div class="footer__widget-title mb-20">
                                                <h4>About The Store</h4>
                                            </div>
                                            <div class="footer__widget-content">
                                                <p class="footer-text mb-35">Our mission statement is to provide the things that you can take on rent simply.</p>



                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer__bottom">
                <div class="container">
                    <div class="footer__bottom-content pt-55 pb-45">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="footer__links text-center mb-25">
                                    <p>


                                        <a href="faq.html">My Booking</a>
                                        <a href="faq.html">Help</a>
                                        <a href="faq.html">Customer Service</a>
                                        <a href="faq.html">Support</a>
                                        <a href="faq.html">Most Populars</a>
                                        <a href="faq.html">New Arrivals</a>
                                        <a href="faq.html">Special Products </a>
                                        <a href="faq.html">Manufacturers</a>
                                        <br>
                                        <a href="faq.html">Garden Equipments</a>
                                        <a href="faq.html">Powers And Hand Tools </a>
                                        <a href="faq.html">Utensil &amp; Gadget </a>
                                        <a href="faq.html">Printers</a>
                                        <a href="faq.html">Projectors</a>
                                        <a href="faq.html">Scanners</a>
                                        <a href="faq.html">Store</a>
                                        <a href="faq.html">Business</a>
                                    </p>
                                </div>
                                <div class="payment-image text-center mb-25">
                                    <a href="contact.html"><img src="assets/img/payment/payment.png" alt=""></a>
                                </div>
                                <div class="copy-right-area text-center">
                                    <p>Copyright © <span>Rent It.</span> All Rights Reserved. Powered by <a href="#"><span class="main-color">Theme_Pure.</span></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer-end -->

pythonProject5/RentX/templates/includes/header.html
{% load static %}
<!-- header-start -->
    <header class="header d-blue-bg">
        <div class="header-top">
            <div class="container">
                <div class="header-inner">
                    <div class="row align-items-center">
                        <div class="col-xl-6 col-lg-7">
                            <div class="header-inner-start">
                                <div class="support d-none d-sm-block">
                                    {% if user.is_authenticated %}
                                        <p>Welcome
                                            {% if user.first_name == "" %}
                                                {{ user.email }}
                                            {% else %}
                                                {{ user.first_name }} {{ user.last_name }}
                                            {% endif %}
                                        </p>
                                    {% else %}
                                        <p>Login first</p>
                                    {% endif %}

                                </div>

                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-5 d-none d-lg-block">
                            <div class="header-inner-end text-md-end">
                                <div class="ovic-menu-wrapper">
                                    <ul>
                                        <li><a href="about.html">About Us</a></li>
                                        <li><a href="contact.html">Order Tracking</a></li>
                                        <li><a href="contact.html">Contact Us</a></li>
                                        <li><a href="faq.html">FAQs</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-mid">
            <div class="container">
                <div class="heade-mid-inner">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4">
                            <div class="header__info">
                                <div class="logo">
                                    <a href="index.html" class="logo-image"><img src="{% static 'assets/img/logo/rentlogo.jpg' %}" alt="logo"></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-5 col-lg-4 d-none d-lg-block">
                            <div class="header__search">
                                <form action="#">
                                    <div class="header__search-box">
                                        <input class="search-input" type="text" placeholder="I'm looking for...">
                                        <button class="button" type="submit"><i class="far fa-search"></i></button>
                                    </div>
                                    <div class="header__search-cat">
                                        <select>
                                            <option>All Categories</option>
                                            <option>Best Seller Products</option>
                                            <option>Top 10 Offers</option>
                                            <option>New Arrivals</option>
                                            <option>Phones &amp; Tablets</option>
                                            <option>Electronics &amp; Digital</option>
                                            <option>Fashion &amp; Clothings</option>
                                            <option>Jewelry &amp; Watches</option>
                                            <option>Health &amp; Beauty</option>
                                            <option>Sound &amp; Speakers</option>
                                            <option>TV &amp; Audio</option>
                                            <option>Computers</option>
                                        </select>
                                    </div>
                                </form>
                            </div>
                        </div>


            {% include 'includes/modal.html' %}
            </div>
        </div>
        <div class="header__bottom">
            <div class="container">
                <div class="row g-0 align-items-center">
                    <div class="col-lg-3">
                        <div class="cat__menu-wrapper side-border d-none d-lg-block">
                            <div class="cat-toggle">
                                <button type="button" class="cat-toggle-btn cat-toggle-btn-1"><i class="fal fa-bars"></i> Shop by department</button>
                                <div class="cat__menu">
                                    <nav id="mobile-menu" style="display: block;">
                                        <ul>


                                           {% for i in main_category %}
                                          <li>
                                            <a href="shop.html" >{{i.name}} <i class="far fa-angle-down"></i></a>
                                                <ul class="mega-menu">
                                                    {% for cat in i.category_set.all %}
                                                    <li><a href="shop.html" style="color:orange;">{{cat.name}}</a>
                                                        <ul class="mega-item">
                                                            {% for sub_cat in cat.sub_category_set.all %}
                                                            <li><a href="product-details.html">{{sub_cat.name}}</a></li>
                                                            {% endfor %}
                                                        </ul>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                            {% endfor %}





                                           <!-- <li><a href="shop.html">Health &amp; Beauty</a></li> -->
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-3">
                      <div class="header__bottom-left d-flex d-xl-block align-items-center">
                        <div class="side-menu d-lg-none mr-20">
                          <button type="button" class="side-menu-btn offcanvas-toggle-btn"><i class="fas fa-bars"></i></button>
                        </div>
                        <div class="main-menu d-none d-lg-block">
                            <nav>
                                <ul>
                                    <li>
                                        <a href="{% url 'home' %}" class="active">Home</a>
                                          </li>
                                    <li><a href="{% url 'about' %}">About Us</a></li>

                                         <li><a href="{% url 'contact' %}">Contact Us</a></li>

                                        <li><a href="{% url 'product' %}">Product</a></li>

                                    <li><a href="blog.html">My Orders <i class="far fa-angle-down"></i></a>
                                        <ul class="submenu">
                                            <li><a href="blog.html">Orders</a></li>
                                            <li><a href="blog-details.html">Order Tracking</a></li>
                                        </ul>
                                    </li>

                                </ul>
                            </nav>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-9">
                        <div class="shopeing-text text-sm-end">
                            <p>Spend $120 more and get free shipping!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>



<!-- offcanvas area start -->
    <div class="offcanvas__area">
        <div class="offcanvas__wrapper">
        <div class="offcanvas__close">
            <button class="offcanvas_close-btn" id="offcanvas_close-btn">
                <i class="fal fa-times"></i>
            </button>
        </div>
        <div class="offcanvas__content">
            <div class="offcanvas__logo mb-40">
                <a href="index.html">
                <img src="{% static 'assets/img/logo/logo-white.png' %}" alt="logo">
                </a>
            </div>
            <div class="offcanvas__search mb-25">
                <form action="#">
                    <input type="text" placeholder="What are you searching for?">
                    <button type="submit" ><i class="far fa-search"></i></button>
                </form>
            </div>
            <div class="mobile-menu fix"></div>
            <div class="offcanvas__action">

            </div>
        </div>
        </div>
    </div>
    <!-- offcanvas area end -->
    <div class="body-overlay"></div>
    <!-- offcanvas area end -->

pythonProject5/RentX/templates/includes/modal.html
<div class="col-xl-4 col-lg-5 col-md-8 col-sm-8">
    <div class="header-action">

                                {% if user.is_authenticated %}
                                 <div class="block-userlink">
                                    <a class="icon-link" href="{% url 'profile' %}">
                                    <i class="flaticon-user"></i>
                                    <span class="text">
                                    <span class="sub">Logout</span>
                                    My Profile </span>
                                    </a>
                                </div>
                                {% else %}

                                <div class="block-userlink">
                                    <a class="icon-link" href="{% url 'login' %}">
                                    <i class="flaticon-user"></i>
                                    <span class="text">
                                    <span class="sub">Login </span>
                                    My Account </span>
                                    </a>
                                </div>
                                {% endif %}

                                <div class="block-wishlist action">
                                    <a class="icon-link" href="wishlist.html">
                                    <i class="flaticon-heart"></i>
                                    <span class="count">0</span>
                                    <span class="text">
                                    <span class="sub">Favorite</span>
                                    My Wishlist </span>
                                    </a>
                                </div>
                                <div class="block-cart action">
                                    <a class="icon-link" href="cart.html">
                                    <i class="flaticon-shopping-bag"></i>
                                    <span class="count">{{request.session.cart|length}}</span>
                                    <span class="text">
                                    <span class="sub">Your Cart:</span>
                                    $00.00 </span>
                                    </a>
                                    <div class="cart">
                                        <div class="cart__mini">
                                            <ul>
                                                <li>
                                                  <div class="cart__title">
                                                    <h4>Your Cart</h4>
                                                    <span>({{request.session.cart|length}}Item in Cart)</span>
                                                  </div>
                                                </li>


                                                {% for key,value in request.session.cart.items %}
                                                <li>
                                                  <div class="cart__item d-flex justify-content-between align-items-center">
                                                    <div class="cart__inner d-flex">
                                                      <div class="cart__thumb">
                                                        <a href="product-details.html">
                                                          <img src="{{value.featured_image}}" alt="">
                                                        </a>
                                                      </div>
                                                      <div class="cart__details">
                                                        <h6><a href="product-details.html"> {{value.product_name}}  </a></h6>
                                                        <div class="cart__price">
                                                          <span>₹{{value.price}}</span>
                                                        </div>
                                                      </div>
                                                    </div>
                                                    <div class="cart__del">
                                                        <a href="{% url 'cart_clear' %}"><i class="fal fa-times"></i></a>
                                                    </div>
                                                  </div>
                                                </li>
                                                {% endfor %}


                                                <li>
                                                  <div class="cart__sub d-flex justify-content-between align-items-center">
                                                    <h6>Subtotal</h6>
                                                    <span class="cart__sub-total">₹{{cart_total_amount}}</span>
                                                  </div>
                                                </li>
                                                <li>
                                                    <a href="{% url 'cart_detail' %}" class="wc-cart mb-10">View cart</a>
                                                    <a href="checkout.html" class="wc-checkout">Checkout</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>